[versions]
kotlin = "2.4.20"
kotlinx-serialization = "1.11.0"

[libraries]
detektGradle = { module = "dev.jonpoulton.blueprint:detekt-rules", version = "2.4.2" }
junit4 = { module = "junit:junit", version = "4.13.2" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktfmt = { module = "com.facebook:ktfmt", version = "0.64" } # only used in ktfmt.sh

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "6.1.1" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.6" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
licensee = { id = "app.cash.licensee", version = "1.14.1" }
publish = { id = "com.vanniktech.maven.publish", version = "0.37.0" }
straitjacket = { id = "dev.jonpoulton.straitjacket", version = "0.1.0" }
