

package fallback.serializer.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link fallback.serializer.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  private void run(String fileName) {
    runTest("compiler-tests/src/test/data/box/" + fileName);
  }

  @Test
  @TestMetadata("ActualOnlyFallbackEntry.kt")
  public void testActualOnlyFallbackEntry() {
    run("ActualOnlyFallbackEntry.kt");
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("ClassSerialName.kt")
  public void testClassSerialName() {
    run("ClassSerialName.kt");
  }

  @Test
  @TestMetadata("CoerceInputValues.kt")
  public void testCoerceInputValues() {
    run("CoerceInputValues.kt");
  }

  @Test
  @TestMetadata("CompanionObject.kt")
  public void testCompanionObject() {
    run("CompanionObject.kt");
  }

  @Test
  @TestMetadata("DecodesKnownEntries.kt")
  public void testDecodesKnownEntries() {
    run("DecodesKnownEntries.kt");
  }

  @Test
  @TestMetadata("DecodesUnknownAsFallback.kt")
  public void testDecodesUnknownAsFallback() {
    run("DecodesUnknownAsFallback.kt");
  }

  @Test
  @TestMetadata("EncodesBySerialName.kt")
  public void testEncodesBySerialName() {
    run("EncodesBySerialName.kt");
  }

  @Test
  @TestMetadata("ExpectActualEnum.kt")
  public void testExpectActualEnum() {
    run("ExpectActualEnum.kt");
  }

  @Test
  @TestMetadata("NestedEnum.kt")
  public void testNestedEnum() {
    run("NestedEnum.kt");
  }

  @Test
  @TestMetadata("NoSerializerWithoutFallbackEntry.kt")
  public void testNoSerializerWithoutFallbackEntry() {
    run("NoSerializerWithoutFallbackEntry.kt");
  }

  @Test
  @TestMetadata("PropertyOfSerializableClass.kt")
  public void testPropertyOfSerializableClass() {
    run("PropertyOfSerializableClass.kt");
  }

  @Test
  @TestMetadata("ReflectionLookup.kt")
  public void testReflectionLookup() {
    run("ReflectionLookup.kt");
  }

  @Test
  @TestMetadata("SerialInfoAnnotations.kt")
  public void testSerialInfoAnnotations() {
    run("SerialInfoAnnotations.kt");
  }

  @Test
  @TestMetadata("UnknownValuesInCollections.kt")
  public void testUnknownValuesInCollections() {
    run("UnknownValuesInCollections.kt");
  }
}
