

package fallback.serializer.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link fallback.serializer.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class FallbackFirstDiagnosticTestGenerated extends AbstractFallbackFirstDiagnosticTest {
  private void run(String fileName) {
    runTest("compiler-tests/src/test/data/diagnostic/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("DifferentActualFallbackEntry.kt")
  public void testDifferentActualFallbackEntry() {
    run("DifferentActualFallbackEntry.kt");
  }

  @Test
  @TestMetadata("ExpectOnlyFallbackEntry.kt")
  public void testExpectOnlyFallbackEntry() {
    run("ExpectOnlyFallbackEntry.kt");
  }

  @Test
  @TestMetadata("FallbackOutsideEnumEntry.kt")
  public void testFallbackOutsideEnumEntry() {
    run("FallbackOutsideEnumEntry.kt");
  }

  @Test
  @TestMetadata("MissingSerializableAnnotation.kt")
  public void testMissingSerializableAnnotation() {
    run("MissingSerializableAnnotation.kt");
  }

  @Test
  @TestMetadata("MultipleFallbackEntries.kt")
  public void testMultipleFallbackEntries() {
    run("MultipleFallbackEntries.kt");
  }

  @Test
  @TestMetadata("SerializableWithOtherSerializer.kt")
  public void testSerializableWithOtherSerializer() {
    run("SerializableWithOtherSerializer.kt");
  }
}
